#site
name: "Unclassed Blog"
url: https://unclassed.ca/jekyllsite
baseurl: "/jekyllsite"

#Cover Page
coverheader: "Hey I'm Tyler"
coversub: "This is my blog where I will post about technology, life, farming, and more!"

collections:
  authors:
