#site
name: "Unclassed Blog"
url: https://unclassed.ca
baseurl: 
permalink: /:year/:month/:day/:title/ 


#Cover Page
coverheader: "Hey I'm Tyler"
coversub: "This is my blog where I will post about technology, life, farming, and more!"


collections:
  authors:


#Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


#Other
markdown: kramdown


kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge 
